name: Validate Branch Name

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          echo "Branch name: $BRANCH_NAME"

            if [[ ! "$BRANCH_NAME" =~ ^((fix|feature|bug|bugfix|hotfix|release|copilot|fix-[0-9]+-[a-z0-9.-]+)\/([a-z0-9.-]+)|fix-[0-9]+-[a-z0-9.-]+|[0-9]+\/merge|main|master|develop)$ ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            echo "Branch names must match the following patterns: feature/slug, bug/slug, bugfix/slug, hotfix/slug, release/slug, copilot/slug, <pr-number>/merge, main, master, develop"
            exit 1
          fi

          echo "✅ Branch name is valid."
